import 'category.dart';

/// بذور التصنيف السعودية (SAUDI_MARKET_SPEC §6).
///
/// [merchantSeeds]: تطابق اسم متجر معروف → مفتاح تصنيف (يُستخدم كبذور أولية
/// لـ merchant_category_map).
/// [keywordRules]: كلمات مفتاحية تظهر داخل اسم المتجر → تصنيف.
class CategorySeeds {
  CategorySeeds._();

  /// أسماء متاجر شائعة (تطابق بالاحتواء، حروف كبيرة).
  static final Map<String, String> keywordRules = {
    // Egypt merchants
    // Note: "Fawry" is a payment gateway, not a merchant — handled by
    // PaymentAggregators (stripped to the real merchant), so no category seed.
    'BREADFAST': Categories.restaurants.key,
    'TALABAT': Categories.restaurants.key,
    'ELMENUS': Categories.restaurants.key,
    'SWVL': Categories.transport.key,
    'ORANGE': Categories.bills.key,
    'VODAFONE': Categories.bills.key,
    'ETISALAT': Categories.bills.key,
    // Gulf delivery/grocery
    'HUNGERSTATION': Categories.restaurants.key,
    'طلبات': Categories.restaurants.key,
    'MRSOOL': Categories.restaurants.key,
    'مرسول': Categories.restaurants.key,
    'SPINNEYS': Categories.groceries.key,
    'NANA': Categories.groceries.key,
    'INSTASHOP': Categories.groceries.key,
    // تسوق
    'JARIR': Categories.shopping.key,
    'EXTRA': Categories.shopping.key,
    'AMAZON': Categories.shopping.key,
    'NOON': Categories.shopping.key,
    // بقالة
    'PANDA': Categories.groceries.key,
    'بنده': Categories.groceries.key,
    'DANUBE': Categories.groceries.key,
    'TAMIMI': Categories.groceries.key,
    'LULU': Categories.groceries.key,
    'CARREFOUR': Categories.groceries.key,
    'OTHAIM': Categories.groceries.key,
    'العثيم': Categories.groceries.key,
    // مطاعم
    'MCDONALD': Categories.restaurants.key,
    'HERFY': Categories.restaurants.key,
    'KUDU': Categories.restaurants.key,
    'ALBAIK': Categories.restaurants.key,
    'البيك': Categories.restaurants.key,
    'BURGER': Categories.restaurants.key,
    'SHAWARMA': Categories.restaurants.key,
    // كافيهات
    'STARBUCKS': Categories.cafes.key,
    'BARNS': Categories.cafes.key,
    'بارنز': Categories.cafes.key,
    'DUNKIN': Categories.cafes.key,
    'ARABICA': Categories.cafes.key,
    'DOSE': Categories.cafes.key,
    // مواصلات
    'UBER': Categories.transport.key,
    'CAREEM': Categories.transport.key,
    'كريم': Categories.transport.key,
    'JEENY': Categories.transport.key,
    // وقود
    'ARAMCO': Categories.fuel.key,
    'PETROMIN': Categories.fuel.key,
    'SASCO': Categories.fuel.key,
    'ساسكو': Categories.fuel.key,
    // فواتير
    'STC': Categories.bills.key,
    'MOBILY': Categories.bills.key,
    'ZAIN': Categories.bills.key,
    // اشتراكات
    'NETFLIX': Categories.subscriptions.key,
    'SHAHID': Categories.subscriptions.key,
    'شاهد': Categories.subscriptions.key,
    'SPOTIFY': Categories.subscriptions.key,
    'ICLOUD': Categories.subscriptions.key,
    'OSN': Categories.subscriptions.key,
    // صحة
    'NAHDI': Categories.health.key,
    'النهدي': Categories.health.key,
    'ALDAWAA': Categories.health.key,
    'الدواء': Categories.health.key,
    'SEIF': Categories.health.key,
    'EZABY': Categories.health.key,
    'العزبي': Categories.health.key,
    // ── Extra Egypt merchants ──
    'KOSHARY': Categories.restaurants.key,
    'MOMEN': Categories.restaurants.key,
    'BUFFALO BURGER': Categories.restaurants.key,
    'CILANTRO': Categories.cafes.key,
    'COSTA': Categories.cafes.key,
    'BEANO': Categories.cafes.key,
    'SEOUDI': Categories.groceries.key,
    'KAZYON': Categories.groceries.key,
    'كازيون': Categories.groceries.key,
    'HYPER ONE': Categories.groceries.key,
    'RAGAB': Categories.groceries.key,
    'GOURMET': Categories.groceries.key,
    'BTECH': Categories.shopping.key,
    'JUMIA': Categories.shopping.key,
    'WATANIYA': Categories.fuel.key,
    'وطنية': Categories.fuel.key,
    'CHILLOUT': Categories.fuel.key,
    'INDRIVE': Categories.transport.key,
    'DIDI': Categories.transport.key,
    'VOX': Categories.entertainment.key,
    'ANGHAMI': Categories.subscriptions.key,
    'WATCH IT': Categories.subscriptions.key,
    'YOUTUBE': Categories.subscriptions.key,
    'DISNEY': Categories.subscriptions.key,
    'APPLE.COM': Categories.subscriptions.key,
    // ── Extra Gulf merchants ──
    'DELIVEROO': Categories.restaurants.key,
    'ZOMATO': Categories.restaurants.key,
    'UNION COOP': Categories.groceries.key,
    'CHOITHRAMS': Categories.groceries.key,
    'AL MAYA': Categories.groceries.key,
    'WEST ZONE': Categories.groceries.key,
    'IKEA': Categories.shopping.key,
    'SHARAF DG': Categories.shopping.key,
    'CENTREPOINT': Categories.shopping.key,
    'NAMSHI': Categories.shopping.key,
    'ADNOC': Categories.fuel.key,
    'ENOC': Categories.fuel.key,
    'EPPCO': Categories.fuel.key,
    'EMARAT': Categories.fuel.key,
    'TIM HORTONS': Categories.cafes.key,
    'CARIBOU': Categories.cafes.key,
    'OOREDOO': Categories.bills.key,
    'BATELCO': Categories.bills.key,
    'DEWA': Categories.bills.key,
    // ── Fitness / beauty / charity / pets / insurance ──
    'FITNESS': Categories.fitness.key,
    'نادي رياضي': Categories.fitness.key,
    'GYMNASIUM': Categories.fitness.key,
    'SALON': Categories.beauty.key,
    'صالون': Categories.beauty.key,
    'BARBER': Categories.beauty.key,
    'حلاق': Categories.beauty.key,
    'تبرع': Categories.charity.key,
    'صدقة': Categories.charity.key,
    'زكاة': Categories.charity.key,
    'جمعية خيرية': Categories.charity.key,
    'CHARITY': Categories.charity.key,
    'بيطري': Categories.pets.key,
    'VETERINARY': Categories.pets.key,
    'PETSHOP': Categories.pets.key,
    'تأمين': Categories.insurance.key,
    'INSURANCE': Categories.insurance.key,
    'BUPA': Categories.insurance.key,
    'بوبا': Categories.insurance.key,
    'TAWUNIYA': Categories.insurance.key,
    'التعاونية': Categories.insurance.key,
    // ── مطاعم / وجبات سريعة (خليج + مصر) ──
    'SHAWARMER': Categories.restaurants.key,
    'AL TAZAJ': Categories.restaurants.key,
    'التازج': Categories.restaurants.key,
    'KEBABJI': Categories.restaurants.key,
    'MAMA NOURA': Categories.restaurants.key,
    'ماما نورة': Categories.restaurants.key,
    'SHAKE SHACK': Categories.restaurants.key,
    'TEXAS CHICKEN': Categories.restaurants.key,
    'POPEYES': Categories.restaurants.key,
    'HARDEES': Categories.restaurants.key,
    'هارديز': Categories.restaurants.key,
    'BURGER KING': Categories.restaurants.key,
    'MAESTRO PIZZA': Categories.restaurants.key,
    'LITTLE CAESARS': Categories.restaurants.key,
    'PAPA JOHNS': Categories.restaurants.key,
    'PIZZA HUT': Categories.restaurants.key,
    'DOMINOS': Categories.restaurants.key,
    'دومينوز': Categories.restaurants.key,
    'SUBWAY': Categories.restaurants.key,
    'WINGSTOP': Categories.restaurants.key,
    'FIVE GUYS': Categories.restaurants.key,
    'CHIPOTLE': Categories.restaurants.key,
    'COOK DOOR': Categories.restaurants.key,
    'كوك دور': Categories.restaurants.key,
    'ABOU TAREK': Categories.restaurants.key,
    'ابو طارق': Categories.restaurants.key,
    'FELFELA': Categories.restaurants.key,
    'فلفلة': Categories.restaurants.key,
    'HADRAMOUT': Categories.restaurants.key,
    'حضرموت': Categories.restaurants.key,
    'ZOOBA': Categories.restaurants.key,
    'زووبا': Categories.restaurants.key,
    // ── كافيهات ──
    'DR CAFE': Categories.cafes.key,
    'دكتور كافيه': Categories.cafes.key,
    'HALF MILLION': Categories.cafes.key,
    'نص مليون': Categories.cafes.key,
    'JOFFREYS': Categories.cafes.key,
    'GLORIA JEANS': Categories.cafes.key,
    'SECOND CUP': Categories.cafes.key,
    'CINNABON': Categories.cafes.key,
    'KRISPY KREME': Categories.cafes.key,
    // ── بقالة / سوبرماركت ──
    'BINDAWOOD': Categories.groceries.key,
    'بن داود': Categories.groceries.key,
    'NESTO': Categories.groceries.key,
    'نستو': Categories.groceries.key,
    'ALMEERA': Categories.groceries.key,
    'الميرة': Categories.groceries.key,
    'GRANDIOSE': Categories.groceries.key,
    'AWLAD RAGAB': Categories.groceries.key,
    'اولاد رجب': Categories.groceries.key,
    'METRO MARKET': Categories.groceries.key,
    'مترو ماركت': Categories.groceries.key,
    'FATHALLA': Categories.groceries.key,
    'فتح الله': Categories.groceries.key,
    'KHEIR ZAMAN': Categories.groceries.key,
    'خير زمان': Categories.groceries.key,
    // ── صحة / صيدليات / مستشفيات ──
    'WHITES': Categories.health.key,
    'AL HABIB': Categories.health.key,
    'السليمان الحبيب': Categories.health.key,
    'DALLAH': Categories.health.key,
    'دلة': Categories.health.key,
    'SAUDI GERMAN': Categories.health.key,
    'السعودي الالماني': Categories.health.key,
    'MOUWASAT': Categories.health.key,
    'المواساة': Categories.health.key,
    'ANDALUSIA': Categories.health.key,
    'الاندلسية': Categories.health.key,
    'MAGRABI': Categories.health.key,
    'مغربي': Categories.health.key,
    'CLEOPATRA': Categories.health.key,
    'كليوباترا': Categories.health.key,
    'DAR AL FOUAD': Categories.health.key,
    'دار الفؤاد': Categories.health.key,
    'VEZEETA': Categories.health.key,
    'فيزيتا': Categories.health.key,
    'ROSHDY': Categories.health.key,
    'روشدي': Categories.health.key,
    // ── وقود ──
    'MISR PETROLEUM': Categories.fuel.key,
    'مصر للبترول': Categories.fuel.key,
    'TOTALENERGIES': Categories.fuel.key,
    // ── مواصلات ──
    'BOLT': Categories.transport.key,
    'بولت': Categories.transport.key,
    'SAPTCO': Categories.transport.key,
    'سابتكو': Categories.transport.key,
    'مترو الانفاق': Categories.transport.key,
    'YANGO': Categories.transport.key,
    'يانجو': Categories.transport.key,
    // ── تسوق / تجزئة ──
    'SHEIN': Categories.shopping.key,
    'شي ان': Categories.shopping.key,
    'MAX FASHION': Categories.shopping.key,
    'SPLASH': Categories.shopping.key,
    'سبلاش': Categories.shopping.key,
    'BABYSHOP': Categories.shopping.key,
    'بيبي شوب': Categories.shopping.key,
    'REDTAG': Categories.shopping.key,
    'HOME CENTRE': Categories.shopping.key,
    'هوم سنتر': Categories.shopping.key,
    'ZARA': Categories.shopping.key,
    'NIKE': Categories.shopping.key,
    'ADIDAS': Categories.shopping.key,
    'TRADELINE': Categories.shopping.key,
    'تريد لاين': Categories.shopping.key,
    'VIRGIN': Categories.shopping.key,
    // ── توصيل طعام ──
    'JAHEZ': Categories.restaurants.key,
    'جاهز': Categories.restaurants.key,
    'THE CHEFZ': Categories.restaurants.key,
    'ذا شفز': Categories.restaurants.key,
    'TOYOU': Categories.restaurants.key,
    'RABBIT': Categories.groceries.key,
    'رابت': Categories.groceries.key,
    // ── ترفيه / سينما ──
    'MUVI': Categories.entertainment.key,
    'موفي': Categories.entertainment.key,
    'REEL CINEMAS': Categories.entertainment.key,
    'CINEPOLIS': Categories.entertainment.key,
    'RENAISSANCE': Categories.entertainment.key,
    // ── سفر / طيران ──
    'SAUDIA': Categories.travel.key,
    'السعودية للطيران': Categories.travel.key,
    'FLYNAS': Categories.travel.key,
    'طيران ناس': Categories.travel.key,
    'FLYADEAL': Categories.travel.key,
    'EMIRATES': Categories.travel.key,
    'EGYPTAIR': Categories.travel.key,
    'مصر للطيران': Categories.travel.key,
    'QATAR AIRWAYS': Categories.travel.key,
    'ETIHAD': Categories.travel.key,
    'ALMOSAFER': Categories.travel.key,
    'المسافر': Categories.travel.key,
    'WEGO': Categories.travel.key,
    'ويجو': Categories.travel.key,
    'TAJAWAL': Categories.travel.key,
    'AGODA': Categories.travel.key,
    'BOOKING': Categories.travel.key,
    // ── لياقة ──
    'GOLDS GYM': Categories.fitness.key,
    'BODYMASTERS': Categories.fitness.key,
    'بادي ماسترز': Categories.fitness.key,
    'LEEJAM': Categories.fitness.key,
    'FITNESS FIRST': Categories.fitness.key,
    // ── عناية شخصية ──
    'SEPHORA': Categories.beauty.key,
    'سيفورا': Categories.beauty.key,
    'FACES': Categories.beauty.key,
    'NSTYLE': Categories.beauty.key,
    // ── تبرعات ──
    'ORMAN': Categories.charity.key,
    'الاورمان': Categories.charity.key,
    'مصر الخير': Categories.charity.key,
    'رسالة': Categories.charity.key,
    'EHSAN': Categories.charity.key,
    'احسان': Categories.charity.key,
    'بيت الزكاة': Categories.charity.key,
    // ── حيوانات أليفة ──
    'PETZONE': Categories.pets.key,
    'بت زون': Categories.pets.key,
    // ── تأمين ──
    'MEDGULF': Categories.insurance.key,
    'ميدغلف': Categories.insurance.key,
    'AXA': Categories.insurance.key,
    'اكسا': Categories.insurance.key,
    // ── تعليم ──
    'UDEMY': Categories.education.key,
    'COURSERA': Categories.education.key,
    'NAGWA': Categories.education.key,
    'نجوى': Categories.education.key,
    // ── mali_financial_corpus seed (new keywords only; deduped) ──
    // Dropped generic substrings (METRO/TOTAL/COOP/LAB) that would mis-match
    // longer merchant names via containment; HyperPanda mapped to groceries.
    'TAXI': Categories.transport.key,
    'UBEREATS': Categories.restaurants.key,
    'NOONFOOD': Categories.restaurants.key,
    'CAREEMNOW': Categories.restaurants.key,
    'AMZN': Categories.shopping.key,
    'ALIEXPRESS': Categories.shopping.key,
    'TEMU': Categories.shopping.key,
    'HYPERPANDA': Categories.groceries.key,
    'GOOGLE': Categories.subscriptions.key,
    'MICROSOFT': Categories.subscriptions.key,
    'ADOBE': Categories.subscriptions.key,
    'META ADS': Categories.subscriptions.key,
    'FACEBOOK ADS': Categories.subscriptions.key,
    'GOOGLE ADS': Categories.subscriptions.key,
    'TIKTOK ADS': Categories.subscriptions.key,
    'LINKEDIN ADS': Categories.subscriptions.key,
    'SHELL': Categories.fuel.key,
    'MOBIL': Categories.fuel.key,
    'WATANIA': Categories.fuel.key,
    'AIRBNB': Categories.travel.key,
    'EXPEDIA': Categories.travel.key,
    'SKYSCANNER': Categories.travel.key,
    'FLYDUBAI': Categories.travel.key,
    'PHARMA': Categories.health.key,
    'ELEZABY': Categories.health.key,
    'EDX': Categories.education.key,
    'BRITISH COUNCIL': Categories.education.key,
    'DUOLINGO': Categories.education.key,
    // Generic English patterns (broad, so come after specifics)
    'RESTAURANT': Categories.restaurants.key,
    'PHARMACY': Categories.health.key,
    'HOSPITAL': Categories.health.key,
    'CLINIC': Categories.health.key,
    'PETROL': Categories.fuel.key,
    'CINEMA': Categories.entertainment.key,
    'MOVIE': Categories.entertainment.key,
    'HOTEL': Categories.travel.key,
    'AIRPORT': Categories.travel.key,
    // Generic Arabic patterns
    'مطعم': Categories.restaurants.key,
    'مقهى': Categories.cafes.key,
    'صيدلية': Categories.health.key,
    'محطة': Categories.fuel.key,
    'مستشفى': Categories.health.key,
    'عيادة': Categories.health.key,
    'سينما': Categories.entertainment.key,
    'فندق': Categories.travel.key,
    'مطار': Categories.travel.key,
  };
}
