// Coupons Phase C3 — Coupon image upload/removal.
//
// The browser sends the file to THIS trusted server route. Everything is
// validated BEFORE any Storage call: admin membership, size, declared MIME
// against the allowlist, and the real file signature (magic bytes). SVG, HTML
// and arbitrary binaries are rejected — the bucket is public-read and there is
// no sanitizer. The object key is generated by the server from the coupon id,
// so a client-supplied filename/directory/extension can never influence it
// (no '../', no foreign prefix, no overwriting another coupon's asset).
import { NextRequest, NextResponse } from "next/server";
import { adminAuthErrorResponse, requireAdmin } from "@/lib/auth-guard";
import { createAdminClient } from "@/lib/supabase-server";
import { mapDatabaseError, safeErrorBody } from "@/lib/coupon-errors.mjs";
import {
  MAX_IMAGE_BYTES,
  storageObjectPath,
  validateImageUpload,
} from "@/lib/coupon-validation.mjs";

const BUCKET = "coupon-assets";

function fail(code: string, status = 400) {
  return NextResponse.json(safeErrorBody(code), { status });
}

export async function POST(req: NextRequest) {
  try {
    await requireAdmin();
  } catch (e) {
    return adminAuthErrorResponse(e);
  }

  const form = await req.formData();
  const couponId = String(form.get("coupon_id") ?? "");
  const file = form.get("file");
  if (!/^[0-9a-f-]{36}$/i.test(couponId)) return fail("not_found");
  if (!(file instanceof File)) return fail("image_unreadable");
  if (file.size > MAX_IMAGE_BYTES) return fail("image_too_large");

  const bytes = new Uint8Array(await file.arrayBuffer());
  // Declared MIME + magic bytes must agree; the extension is derived from the
  // VERIFIED type, never from the uploaded filename.
  const check = validateImageUpload({ size: file.size, mime: file.type, bytes }) as
    { ok: true; extension: string } | { ok: false; error: string };
  if (!check.ok) return fail(check.error);

  const path = storageObjectPath(couponId, check.extension);
  if (!path) return fail("not_found");

  const supabase = await createAdminClient();

  // What the coupon points at today (used for post-upload cleanup).
  const { data: existing } = await supabase
    .from("coupons")
    .select("image_path")
    .eq("id", couponId)
    .maybeSingle();
  const previousPath = (existing?.image_path as string | null) ?? null;

  // ORDER MATTERS: upload the new object FIRST, then repoint the row, then
  // delete the superseded object. The current image is never removed before its
  // replacement is safely stored, and the row never points at a failed upload.
  const upload = await supabase.storage
    .from(BUCKET)
    .upload(path, bytes, { contentType: file.type, upsert: true });
  if (upload.error) {
    console.error("[coupons] image upload", upload.error);
    return fail("storage_failed", 502);
  }

  const { error: updateError } = await supabase
    .from("coupons")
    .update({ image_path: path })
    .eq("id", couponId);
  if (updateError) {
    console.error("[coupons] image path update", updateError);
    // The freshly uploaded object is orphaned rather than leaving the row
    // pointing at something that does not exist; remove it best-effort.
    if (path !== previousPath) await supabase.storage.from(BUCKET).remove([path]);
    return NextResponse.json(safeErrorBody(mapDatabaseError(updateError)), { status: 500 });
  }

  // Only now is the old object superseded — and only when the extension (and
  // therefore the key) actually changed.
  if (previousPath && previousPath !== path && previousPath.startsWith(`coupons/${couponId}/`)) {
    await supabase.storage.from(BUCKET).remove([previousPath]);
  }

  return NextResponse.json({ image_path: path });
}

/**
 * Remove a coupon's image. The coupon stays valid: presentation falls back to
 * its accent colour. Only this coupon's own object is touched.
 */
export async function DELETE(req: NextRequest) {
  try {
    await requireAdmin();
  } catch (e) {
    return adminAuthErrorResponse(e);
  }

  const couponId = req.nextUrl.searchParams.get("coupon_id") ?? "";
  if (!/^[0-9a-f-]{36}$/i.test(couponId)) return fail("not_found");

  const supabase = await createAdminClient();
  const { data: existing } = await supabase
    .from("coupons")
    .select("image_path")
    .eq("id", couponId)
    .maybeSingle();
  const currentPath = (existing?.image_path as string | null) ?? null;

  // Clear the reference first so no window exists where the row points at a
  // deleted object.
  const { error: updateError } = await supabase
    .from("coupons")
    .update({ image_path: null })
    .eq("id", couponId);
  if (updateError) {
    console.error("[coupons] image clear", updateError);
    return NextResponse.json(safeErrorBody(mapDatabaseError(updateError)), { status: 500 });
  }

  if (currentPath && currentPath.startsWith(`coupons/${couponId}/`)) {
    await supabase.storage.from(BUCKET).remove([currentPath]);
  }

  return NextResponse.json({ ok: true });
}
