#!/usr/bin/env python3
"""Generate the Dart and PostgreSQL fold tables for merchant_alias_key_v1.

Both implementations of a frozen cross-platform key function have to agree on
every code point. Hand-transcribing 142 code points into two languages is a
guaranteed source of silent drift — a single wrong character produces a key that
differs only for inputs nobody thought to test, and the failure mode is a
permanent merchant-resolution miss on real user data.

So the tables live in ONE json file and both artifacts are generated from it.
`--check` re-generates and diffs, which is what CI asserts.

Usage:
    python3 tools/coupons/gen_merchant_alias_key.py           # write artifacts
    python3 tools/coupons/gen_merchant_alias_key.py --check   # verify, exit 1 on drift
"""
import io
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TABLES = os.path.join(ROOT, 'docs/coupons/merchant_alias_key_v1.tables.json')
# NOT a `.g.dart` name: app/.gitignore ignores `*.g.dart` because that suffix
# means build_runner output, which is regenerated during the Flutter build.
# These tables are generated by THIS script, which the Flutter build never
# runs, so an ignored file would simply be missing and the app would not
# compile. The GENERATED banner plus the --check CI gate carry the same
# guarantee without fighting the ignore rule.
DART_OUT = os.path.join(ROOT, 'app/lib/features/coupons/merchant_alias_key_tables.dart')
# The SQL half is INJECTED into 0094 between markers rather than written as a
# separate file: a migration in a subdirectory is not applied by `supabase db
# push`, and a second copy anywhere is exactly the drift this script exists to
# stop.
MIGRATION = os.path.join(ROOT, 'supabase/migrations/0094_catalog_merchants.sql')
BEGIN_MARK = '-- >>> BEGIN GENERATED merchant_alias_key_v1 >>>'
END_MARK = '-- <<< END GENERATED merchant_alias_key_v1 <<<'

BANNER = 'GENERATED by tools/coupons/gen_merchant_alias_key.py — DO NOT EDIT BY HAND.'


def esc_dart(cp: int) -> str:
    return '\\u{%04X}' % cp


def sql_literal(codepoints) -> str:
    """A SQL string literal for translate(). Uses U&'...' escapes so the file
    stays pure ASCII — an editor that helpfully re-encodes Arabic would
    otherwise corrupt a frozen contract invisibly."""
    return "U&'" + ''.join('\\%04X' % cp for cp in codepoints) + "'"


def main() -> int:
    t = json.load(io.open(TABLES, encoding='utf-8'))
    assert t['version'] == 1

    diacritics = t['diacritics_removed']
    case_from = [int(k) for k in t['case_folds']]
    case_to = [t['case_folds'][k] for k in t['case_folds']]
    letter_from = [int(k) for k in t['letter_folds']]
    letter_to = [t['letter_folds'][k] for k in t['letter_folds']]
    digit_from = [int(k) for k in t['digit_folds']]
    digit_to = [t['digit_folds'][k] for k in t['digit_folds']]
    keep = t['keep_set']

    # ---- Dart -------------------------------------------------------------
    NL = chr(10)
    SEP = ',' + NL

    def dart_map(frm, to):
        return SEP.join('  0x%04X: 0x%04X' % (f, x) for f, x in zip(frm, to))

    diacritics_lines = SEP.join('  0x%04X' % c for c in diacritics)
    keep_lines = SEP.join('  0x%04X' % c for c in keep)
    case_map = dart_map(case_from, case_to)
    letter_map = dart_map(letter_from, letter_to)
    digit_map = dart_map(digit_from, digit_to)

    dart = f'''// {BANNER}
// Source of truth: docs/coupons/merchant_alias_key_v1.tables.json
// Specification:   docs/coupons/MERCHANT_ALIAS_KEY_V1.md
//
// These tables are FROZEN. Changing one is a new key version (_v2), a
// transactional re-key of every stored alias, an index rebuild and client
// gating — never an edit in place.

/// Code points deleted outright: Arabic diacritics, Quranic signs and tatweel.
const Set<int> kAliasKeyDiacriticsV1 = <int>{{
{diacritics_lines},
}};

/// ASCII case fold. Deliberately NOT `toLowerCase()` — that follows the Unicode
/// default casing table, which PostgreSQL's collation-dependent `lower()` does
/// not match.
const Map<int, int> kAliasKeyCaseFoldsV1 = <int, int>{{
{case_map},
}};

/// Arabic/Persian letter folds. Persian gaf (U+06AF) is deliberately absent —
/// it is a distinct phoneme with no Arabic equivalent, so folding it buys no
/// recall in this market and only creates collisions.
const Map<int, int> kAliasKeyLetterFoldsV1 = <int, int>{{
{letter_map},
}};

/// Arabic-Indic and Eastern Arabic-Indic digits to ASCII. Digits are then KEPT.
const Map<int, int> kAliasKeyDigitFoldsV1 = <int, int>{{
{digit_map},
}};

/// Everything outside this set becomes a single space. Enumerated rather than
/// expressed as ranges or Unicode categories, because both differ between
/// Dart's and PostgreSQL's Unicode versions.
const Set<int> kAliasKeyKeepV1 = <int>{{
{keep_lines},
}};
'''

    # ---- SQL --------------------------------------------------------------
    sql = f'''-- {BANNER}
-- Source of truth: docs/coupons/merchant_alias_key_v1.tables.json
-- Specification:   docs/coupons/MERCHANT_ALIAS_KEY_V1.md
--
-- INJECTED into 0094_catalog_merchants.sql between markers. It is not a
-- standalone migration: a .sql file in a subdirectory is not applied by
-- `supabase db push`, and a second copy would be the drift this design prevents.
--
-- IMMUTABLE is required: the function backs a STORED generated column and a
-- partial unique index. Every operation used here (translate, regexp_replace
-- with an enumerated class, btrim on ASCII space) is collation-independent.
--
-- NEVER `CREATE OR REPLACE` this function. PostgreSQL permits it, does not
-- recompute stored generated columns, and does not rebuild dependent indexes —
-- the result is silently stale keys with no error anywhere.

CREATE OR REPLACE FUNCTION merchant_alias_key_v1(input TEXT)
RETURNS TEXT
LANGUAGE sql
IMMUTABLE
PARALLEL SAFE
RETURNS NULL ON NULL INPUT
AS $$
  SELECT btrim(
    regexp_replace(
      regexp_replace(
        -- step 5: fold Arabic-Indic + Eastern Arabic-Indic digits, KEEP them
        translate(
          -- step 4: letter folds
          translate(
            -- step 3: delete diacritics and tatweel
            translate(
              -- step 2: ASCII case fold only
              translate(input, {sql_literal(case_from)}, {sql_literal(case_to)}),
              {sql_literal(diacritics)}, ''
            ),
            {sql_literal(letter_from)}, {sql_literal(letter_to)}
          ),
          {sql_literal(digit_from)}, {sql_literal(digit_to)}
        ),
        -- step 6: everything outside the KEEP set becomes one space.
        -- Enumerated, never a range: PostgreSQL bracket ranges are
        -- collating-sequence dependent.
        '[^' || {sql_literal(keep)} || ']', ' ', 'g'
      ),
      -- step 7: collapse runs of ASCII space
      ' +', ' ', 'g'
    ),
    ' '  -- step 8: trim ASCII space ONLY (btrim's default set is ASCII space)
  );
$$;

COMMENT ON FUNCTION merchant_alias_key_v1(TEXT) IS
  'FROZEN v1 merchant-name lookup key. See docs/coupons/MERCHANT_ALIAS_KEY_V1.md. Never edit in place.';

-- Domain keys are a SEPARATE contract: digits, dots and hyphens are
-- semantically load-bearing in a hostname, so `7eleven.com` must never fold the
-- way a name does. Takes an ALREADY-EXTRACTED host — URL parsing and IDNA
-- happen upstream on the client, because PostgreSQL ships neither and a
-- mismatched IDNA implementation is exactly the drift this design prevents.
CREATE OR REPLACE FUNCTION merchant_domain_key_v1(input TEXT)
RETURNS TEXT
LANGUAGE sql
IMMUTABLE
PARALLEL SAFE
RETURNS NULL ON NULL INPUT
AS $$
  SELECT CASE
    WHEN host ~ '^[a-z0-9]([a-z0-9-]*[a-z0-9])?(\\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)+$'
      THEN host
    ELSE ''
  END
  FROM (
    SELECT regexp_replace(
             regexp_replace(
               translate(btrim(input, ' '), {sql_literal(case_from)}, {sql_literal(case_to)}),
               '^www\\.', ''
             ),
             '\\.$', ''
           ) AS host
  ) s;
$$;

COMMENT ON FUNCTION merchant_domain_key_v1(TEXT) IS
  'FROZEN v1 merchant-domain lookup key. Host only, never a URL. Never edit in place.';
'''

    migration = io.open(MIGRATION, encoding='utf-8').read()
    head, _, rest = migration.partition(BEGIN_MARK)
    _, _, tail = rest.partition(END_MARK)
    if not head or not tail:
        print('markers missing in %s' % MIGRATION)
        return 2
    injected = head + BEGIN_MARK + chr(10) + sql + END_MARK + tail

    outputs = {DART_OUT: dart, MIGRATION: injected}
    check = '--check' in sys.argv
    drift = False
    for path, content in outputs.items():
        os.makedirs(os.path.dirname(path), exist_ok=True)
        existing = io.open(path, encoding='utf-8').read() if os.path.exists(path) else None
        if check:
            if existing != content:
                print('DRIFT: %s differs from a fresh generation' % os.path.relpath(path, ROOT))
                drift = True
        else:
            io.open(path, 'w', encoding='utf-8').write(content)
            print('wrote %s' % os.path.relpath(path, ROOT))
    if check and not drift:
        print('merchant_alias_key_v1 artifacts match their source tables')
    return 1 if drift else 0


if __name__ == '__main__':
    sys.exit(main())
