-- 0009_corpus_seed.sql
-- Seed banks + wallets (sender IDs) and merchant keywords from
-- mali_financial_corpus. Idempotent: ON CONFLICT / NOT EXISTS guards.
-- NOTE: seed data (matchStrength medium) — verify with real SMS.

INSERT INTO banks (name_ar, name_en, short_code, country_code, sms_senders, supported_currencies, sort_order)
VALUES
  ('البنك الأهلي المصري','National Bank of Egypt','AHLYBANK','EG','["AHLYBANK", "NATBANK", "NBE", "NBEBANK"]'::jsonb,'["EGP"]'::jsonb,0),
  ('بنك مصر','Banque Misr','BANQUEMISR','EG','["BANQUEMISR", "BM", "BMISR"]'::jsonb,'["EGP"]'::jsonb,1),
  ('Commercial International Bank','Commercial International Bank','CIB','EG','["CIB", "CIBBANK", "CIBEG"]'::jsonb,'["EGP"]'::jsonb,2),
  ('QNB Al Ahli','QNB Al Ahli','QNB','EG','["QNB", "QNBA", "QNBALAHLI"]'::jsonb,'["EGP"]'::jsonb,3),
  ('Banque du Caire','Banque du Caire','BANQUEDUCAIRE','EG','["BANQUEDUCAIRE", "BDC", "BDCBANK"]'::jsonb,'["EGP"]'::jsonb,4),
  ('Bank of Alexandria','Bank of Alexandria','ALEXBANK','EG','["ALEXBANK", "BOALEX"]'::jsonb,'["EGP"]'::jsonb,5),
  ('Arab African International Bank','Arab African International Bank','AAIB','EG','["AAIB", "ARABAFRICAN"]'::jsonb,'["EGP"]'::jsonb,6),
  ('Housing and Development Bank','Housing and Development Bank','HDB','EG','["HDB", "HDBANK"]'::jsonb,'["EGP"]'::jsonb,7),
  ('Faisal Islamic Bank Egypt','Faisal Islamic Bank Egypt','FAISALBANK','EG','["FAISALBANK", "FIB", "FIBEG"]'::jsonb,'["EGP"]'::jsonb,8),
  ('Abu Dhabi Islamic Bank Egypt','Abu Dhabi Islamic Bank Egypt','ADIB','EG','["ADIB", "ADIBEG"]'::jsonb,'["EGP"]'::jsonb,9),
  ('Crédit Agricole Egypt','Crédit Agricole Egypt','CAE','EG','["CAE", "CAEGYPT", "CREDITAGRICOLE"]'::jsonb,'["EGP"]'::jsonb,10),
  ('Emirates NBD Egypt','Emirates NBD Egypt','EMIRATESNBD','EG','["EMIRATESNBD", "ENBD", "ENBDEG"]'::jsonb,'["EGP"]'::jsonb,11),
  ('SAIB Bank','SAIB Bank','SAIB','EG','["SAIB", "SAIBBANK"]'::jsonb,'["EGP"]'::jsonb,12),
  ('EGBANK','EGBANK','EGB','EG','["EGB", "EGBANK"]'::jsonb,'["EGP"]'::jsonb,13),
  ('FABMISR','FABMISR','FAB','EG','["FAB", "FABEG", "FABMISR"]'::jsonb,'["EGP"]'::jsonb,14),
  ('HSBC Egypt','HSBC Egypt','HSBC','EG','["HSBC", "HSBCEG"]'::jsonb,'["EGP"]'::jsonb,15),
  ('Ahli United Bank Egypt','Ahli United Bank Egypt','AUB','EG','["AUB", "AUBEG"]'::jsonb,'["EGP"]'::jsonb,16),
  ('MIDBANK','MIDBANK','MID','EG','["MID", "MIDBANK"]'::jsonb,'["EGP"]'::jsonb,17),
  ('Bank NXT','Bank NXT','BANKNXT','EG','["BANKNXT", "NXT", "NXTBANK"]'::jsonb,'["EGP"]'::jsonb,18),
  ('Arab International Bank','Arab International Bank','AIB','EG','["AIB", "AIBEG"]'::jsonb,'["EGP"]'::jsonb,19),
  ('البريد المصري','Egypt Post','EGPOST','EG','["EGPOST", "EGYPTPOST", "POSTEG"]'::jsonb,'["EGP"]'::jsonb,20),
  ('مصرف الراجحي','Al Rajhi Bank','ALRAJHI','SA','["ALRAJHI", "RAJHI"]'::jsonb,'["SAR"]'::jsonb,21),
  ('Saudi National Bank','Saudi National Bank','ALAHLI','SA','["ALAHLI", "NCB", "SNB", "SNBANK"]'::jsonb,'["SAR"]'::jsonb,22),
  ('بنك الرياض','Riyad Bank','RBANK','SA','["RBANK", "RIYAD", "RIYADBANK"]'::jsonb,'["SAR"]'::jsonb,23),
  ('مصرف الإنماء','Alinma Bank','ALINMA','SA','["ALINMA", "INMA"]'::jsonb,'["SAR"]'::jsonb,24),
  ('بنك البلاد','Bank Albilad','ALBILAD','SA','["ALBILAD", "BANKALBILAD"]'::jsonb,'["SAR"]'::jsonb,25),
  ('Saudi Awwal Bank','Saudi Awwal Bank','SAB','SA','["SAB", "SABB", "SAUDIAWWAL"]'::jsonb,'["SAR"]'::jsonb,26),
  ('بنك الجزيرة','Bank AlJazira','ALJAZIRA','SA','["ALJAZIRA", "BAJ", "BANKALJAZIRA"]'::jsonb,'["SAR"]'::jsonb,27),
  ('البنك العربي الوطني','Arab National Bank','ANB','SA','["ANB", "ARABNATIONAL"]'::jsonb,'["SAR"]'::jsonb,28),
  ('البنك السعودي الفرنسي','Banque Saudi Fransi','BSF','SA','["BSF", "FRANSI", "SAUDIFRANSI"]'::jsonb,'["SAR"]'::jsonb,29),
  ('Saudi Investment Bank','Saudi Investment Bank','SAIB_SA','SA','["SAIB", "SAIBSA", "SAUDIINVESTMENT"]'::jsonb,'["SAR"]'::jsonb,30),
  ('Gulf International Bank Saudi Arabia','Gulf International Bank Saudi Arabia','GIB','SA','["GIB", "GIBSA"]'::jsonb,'["SAR"]'::jsonb,31),
  ('D360 Bank','D360 Bank','D360','SA','["D360", "D360BANK"]'::jsonb,'["SAR"]'::jsonb,32),
  ('STC Bank','STC Bank','STCBANK','SA','["STCBANK"]'::jsonb,'["SAR"]'::jsonb,33),
  ('Emirates NBD','Emirates NBD','EMIRATESNBD_AE','AE','["EMIRATESNBD", "ENBD"]'::jsonb,'["AED"]'::jsonb,34),
  ('First Abu Dhabi Bank','First Abu Dhabi Bank','FAB_AE','AE','["FAB", "FABUAE"]'::jsonb,'["AED"]'::jsonb,35),
  ('Abu Dhabi Commercial Bank','Abu Dhabi Commercial Bank','ADCB','AE','["ADCB"]'::jsonb,'["AED"]'::jsonb,36),
  ('Dubai Islamic Bank','Dubai Islamic Bank','DIB','AE','["DIB"]'::jsonb,'["AED"]'::jsonb,37),
  ('Mashreq Bank','Mashreq Bank','MASHREQ','AE','["MASHREQ", "MSHQ"]'::jsonb,'["AED"]'::jsonb,38),
  ('Commercial Bank of Dubai','Commercial Bank of Dubai','CBD','AE','["CBD"]'::jsonb,'["AED"]'::jsonb,39),
  ('RAKBANK','RAKBANK','RAK','AE','["RAK", "RAKBANK"]'::jsonb,'["AED"]'::jsonb,40),
  ('Abu Dhabi Islamic Bank','Abu Dhabi Islamic Bank','ADIB_AE','AE','["ADIB"]'::jsonb,'["AED"]'::jsonb,41),
  ('Wio Bank','Wio Bank','WIO','AE','["WIO", "WIOBANK"]'::jsonb,'["AED"]'::jsonb,42),
  ('Liv Bank','Liv Bank','LIV','AE','["LIV", "LIVBANK"]'::jsonb,'["AED"]'::jsonb,43),
  ('HSBC UAE','HSBC UAE','HSBC_AE','AE','["HSBC", "HSBCUAE"]'::jsonb,'["AED"]'::jsonb,44),
  ('Citibank UAE','Citibank UAE','CITI','AE','["CITI", "CITIBANK"]'::jsonb,'["AED"]'::jsonb,45),
  ('Standard Chartered UAE','Standard Chartered UAE','SCB','AE','["SCB", "STANCHART", "STANDARDCHARTERED"]'::jsonb,'["AED"]'::jsonb,46),
  ('National Bank of Kuwait','National Bank of Kuwait','NBK','KW','["NBK"]'::jsonb,'["KWD"]'::jsonb,47),
  ('Kuwait Finance House','Kuwait Finance House','KFH','KW','["KFH"]'::jsonb,'["KWD"]'::jsonb,48),
  ('Boubyan Bank','Boubyan Bank','BOUBYAN','KW','["BOUBYAN"]'::jsonb,'["KWD"]'::jsonb,49),
  ('Burgan Bank','Burgan Bank','BURGAN','KW','["BURGAN"]'::jsonb,'["KWD"]'::jsonb,50),
  ('Al Ahli Bank of Kuwait','Al Ahli Bank of Kuwait','ABK','KW','["ABK"]'::jsonb,'["KWD"]'::jsonb,51),
  ('Commercial Bank of Kuwait','Commercial Bank of Kuwait','CBK','KW','["CBK"]'::jsonb,'["KWD"]'::jsonb,52),
  ('Qatar National Bank','Qatar National Bank','QNB_QA','QA','["QNB"]'::jsonb,'["QAR"]'::jsonb,53),
  ('Commercial Bank of Qatar','Commercial Bank of Qatar','CBQ','QA','["CBQ"]'::jsonb,'["QAR"]'::jsonb,54),
  ('Dukhan Bank','Dukhan Bank','DUKHAN','QA','["DUKHAN"]'::jsonb,'["QAR"]'::jsonb,55),
  ('Qatar Islamic Bank','Qatar Islamic Bank','QIB','QA','["QIB"]'::jsonb,'["QAR"]'::jsonb,56),
  ('Qatar International Islamic Bank','Qatar International Islamic Bank','QIIB','QA','["QIIB"]'::jsonb,'["QAR"]'::jsonb,57),
  ('Ahlibank Qatar','Ahlibank Qatar','ABQ','QA','["ABQ", "AHLIBANK"]'::jsonb,'["QAR"]'::jsonb,58),
  ('National Bank of Bahrain','National Bank of Bahrain','NBB','BH','["NBB"]'::jsonb,'["BHD"]'::jsonb,59),
  ('Bank of Bahrain and Kuwait','Bank of Bahrain and Kuwait','BBK','BH','["BBK"]'::jsonb,'["BHD"]'::jsonb,60),
  ('Bahrain Islamic Bank','Bahrain Islamic Bank','BISB','BH','["BISB"]'::jsonb,'["BHD"]'::jsonb,61),
  ('Ahli United Bank Bahrain','Ahli United Bank Bahrain','AUB_BH','BH','["AUB"]'::jsonb,'["BHD"]'::jsonb,62),
  ('ila Bank','ila Bank','ILA','BH','["ILA", "ILABANK"]'::jsonb,'["BHD"]'::jsonb,63),
  ('Bank Muscat','Bank Muscat','BANKMUSCAT','OM','["BANKMUSCAT", "MUSCAT"]'::jsonb,'["OMR"]'::jsonb,64),
  ('National Bank of Oman','National Bank of Oman','NBO','OM','["NBO"]'::jsonb,'["OMR"]'::jsonb,65),
  ('Sohar International','Sohar International','SOHAR','OM','["SOHAR", "SOHARBANK"]'::jsonb,'["OMR"]'::jsonb,66),
  ('Ahli Bank Oman','Ahli Bank Oman','AHLIBANK','OM','["AHLIBANK", "AHLIOMAN"]'::jsonb,'["OMR"]'::jsonb,67),
  ('HSBC Oman','HSBC Oman','HSBC_OM','OM','["HSBC", "HSBCOMAN"]'::jsonb,'["OMR"]'::jsonb,68),
  ('Cairo Amman Bank','Cairo Amman Bank','CAB','JO','["CAB", "CAIROAMMAN"]'::jsonb,'["JOD"]'::jsonb,69),
  ('Jordan Kuwait Bank','Jordan Kuwait Bank','JKB','JO','["JKB"]'::jsonb,'["JOD"]'::jsonb,70),
  ('Arab Bank','Arab Bank','ARABBANK','JO','["ARABBANK", "ARB"]'::jsonb,'["JOD"]'::jsonb,71),
  ('Bank of Jordan','Bank of Jordan','BOJ','JO','["BOJ"]'::jsonb,'["JOD"]'::jsonb,72),
  ('Jordan Islamic Bank','Jordan Islamic Bank','JIB','JO','["JIB"]'::jsonb,'["JOD"]'::jsonb,73),
  ('Bank Al Etihad','Bank Al Etihad','ETIHAD','JO','["ETIHAD", "ETIHADBANK"]'::jsonb,'["JOD"]'::jsonb,74),
  ('مصرف الرافدين','Rafidain Bank','RAFIDAIN','IQ','["RAFIDAIN"]'::jsonb,'["IQD"]'::jsonb,75),
  ('مصرف الرشيد','Rasheed Bank','RASHEED','IQ','["RASHEED"]'::jsonb,'["IQD"]'::jsonb,76),
  ('Trade Bank of Iraq','Trade Bank of Iraq','TBI','IQ','["TBI"]'::jsonb,'["IQD"]'::jsonb,77),
  ('National Bank of Iraq','National Bank of Iraq','NBI','IQ','["NBI"]'::jsonb,'["IQD"]'::jsonb,78),
  ('Central Bank of Iraq','Central Bank of Iraq','CBI','IQ','["CBI"]'::jsonb,'["IQD"]'::jsonb,79),
  ('Region Trade Bank','Region Trade Bank','RTB','IQ','["RTB", "RTBANK"]'::jsonb,'["IQD"]'::jsonb,80),
  ('Ashur International Bank','Ashur International Bank','ASHUR','IQ','["ASHUR"]'::jsonb,'["IQD"]'::jsonb,81),
  ('Kurdistan International Bank','Kurdistan International Bank','KIB','IQ','["KIB"]'::jsonb,'["IQD"]'::jsonb,82),
  ('Iraqi Islamic Bank','Iraqi Islamic Bank','IIB','IQ','["IIB"]'::jsonb,'["IQD"]'::jsonb,83),
  ('Al Taif Islamic Bank','Al Taif Islamic Bank','ALTAIF','IQ','["ALTAIF", "TAIFBANK"]'::jsonb,'["IQD"]'::jsonb,84),
  ('JPMorgan Chase','JPMorgan Chase','CHASE','US','["CHASE", "JPMCHASE", "JPMORGAN"]'::jsonb,'["USD"]'::jsonb,85),
  ('Bank of America','Bank of America','BAC','US','["BAC", "BANKOFAMERICA", "BOFA"]'::jsonb,'["USD"]'::jsonb,86),
  ('Wells Fargo','Wells Fargo','WELLSFARGO','US','["WELLSFARGO", "WF"]'::jsonb,'["USD"]'::jsonb,87),
  ('Citibank','Citibank','CITI_US','US','["CITI", "CITIBANK"]'::jsonb,'["USD"]'::jsonb,88),
  ('HSBC UK','HSBC UK','HSBC_GB','GB','["HSBC"]'::jsonb,'["GBP"]'::jsonb,89),
  ('Barclays','Barclays','BARCLAYS','GB','["BARCLAYS", "BCS"]'::jsonb,'["GBP"]'::jsonb,90),
  ('Lloyds Bank','Lloyds Bank','LLOYDS','GB','["LLOYDS", "LLOYDSBANK"]'::jsonb,'["GBP"]'::jsonb,91),
  ('NatWest','NatWest','NATWEST','GB','["NATWEST"]'::jsonb,'["GBP"]'::jsonb,92),
  ('Monzo','Monzo','MONZO','GB','["MONZO"]'::jsonb,'["GBP"]'::jsonb,93),
  ('Starling Bank','Starling Bank','STARLING','GB','["STARLING"]'::jsonb,'["GBP"]'::jsonb,94),
  ('N26','N26','N26','DE','["N26"]'::jsonb,'[]'::jsonb,95),
  ('Deutsche Bank','Deutsche Bank','DB','DE','["DB", "DEUTSCHEBANK"]'::jsonb,'[]'::jsonb,96),
  ('BNP Paribas','BNP Paribas','BNP','FR','["BNP", "BNPPARIBAS"]'::jsonb,'[]'::jsonb,97),
  ('Santander','Santander','SANTANDER','ES','["SANTANDER"]'::jsonb,'[]'::jsonb,98),
  ('Ziraat Bank','Ziraat Bank','ZIRAAT','TR','["ZIRAAT"]'::jsonb,'[]'::jsonb,99),
  ('Garanti BBVA','Garanti BBVA','GARANTI','TR','["GARANTI", "GARANTIBBVA"]'::jsonb,'[]'::jsonb,100),
  ('Akbank','Akbank','AKBANK','TR','["AKBANK"]'::jsonb,'[]'::jsonb,101),
  ('State Bank of India','State Bank of India','SBI','IN','["SBI"]'::jsonb,'[]'::jsonb,102),
  ('HDFC Bank','HDFC Bank','HDFC','IN','["HDFC", "HDFCBANK"]'::jsonb,'[]'::jsonb,103),
  ('ICICI Bank','ICICI Bank','ICICI','IN','["ICICI", "ICICIBANK"]'::jsonb,'[]'::jsonb,104),
  ('Axis Bank','Axis Bank','AXIS','IN','["AXIS", "AXISBANK"]'::jsonb,'[]'::jsonb,105),
  ('Vodafone Cash','Vodafone Cash','VFCASH','EG','["VFCASH", "VODAFONECASH"]'::jsonb,'["EGP"]'::jsonb,106),
  ('Orange Cash','Orange Cash','ORANGECASH','EG','["ORANGECASH"]'::jsonb,'["EGP"]'::jsonb,107),
  ('Etisalat Cash','Etisalat Cash','ETISALATCASH','EG','["ETISALATCASH"]'::jsonb,'["EGP"]'::jsonb,108),
  ('WE Pay','WE Pay','WEPAY','EG','["WEPAY"]'::jsonb,'["EGP"]'::jsonb,109),
  ('Fawry','Fawry','FAWRY','EG','["FAWRY", "MYFAWRY"]'::jsonb,'["EGP"]'::jsonb,110),
  ('Aman','Aman','AMAN','EG','["AMAN"]'::jsonb,'["EGP"]'::jsonb,111),
  ('InstaPay','InstaPay','INSTAPAY','EG','["INSTAPAY", "IPN"]'::jsonb,'["EGP"]'::jsonb,112),
  ('stc pay','stc pay','STCPAY','SA','["STCPAY"]'::jsonb,'["SAR"]'::jsonb,113),
  ('urpay','urpay','URPAY','SA','["URPAY"]'::jsonb,'["SAR"]'::jsonb,114),
  ('Hala','Hala','HALA','SA','["HALA", "HALAPAY"]'::jsonb,'["SAR"]'::jsonb,115),
  ('barq','barq','BARQ','SA','["BARQ"]'::jsonb,'["SAR"]'::jsonb,116),
  ('Mobily Pay','Mobily Pay','MOBILYPAY','SA','["MOBILYPAY"]'::jsonb,'["SAR"]'::jsonb,117),
  ('PayBy','PayBy','PAYBY','AE','["PAYBY"]'::jsonb,'["AED"]'::jsonb,118),
  ('e& money','e& money','EANDMONEY','AE','["EANDMONEY", "ETISALATMONEY"]'::jsonb,'["AED"]'::jsonb,119),
  ('Careem Pay','Careem Pay','CAREEMPAY','AE','["CAREEMPAY"]'::jsonb,'["AED"]'::jsonb,120),
  ('Ooredoo Money','Ooredoo Money','OOREDOOMONEY','QA','["OOREDOOMONEY"]'::jsonb,'["QAR"]'::jsonb,121),
  ('KNET','KNET','KNET','KW','["KNET"]'::jsonb,'["KWD"]'::jsonb,122),
  ('BenefitPay','BenefitPay','BENEFITPAY','BH','["BENEFITPAY"]'::jsonb,'["BHD"]'::jsonb,123)
ON CONFLICT (short_code) DO NOTHING;

INSERT INTO merchant_keywords (keyword, category_key, country_code, language, is_active)
SELECT v.keyword, v.category_key, 'ALL', 'any', true
FROM (VALUES
  ('UBER','transport'),
  ('CAREEM','transport'),
  ('DIDI','transport'),
  ('TAXI','transport'),
  ('SWVL','transport'),
  ('BOLT','transport'),
  ('YANGO','transport'),
  ('METRO','transport'),
  ('TALABAT','restaurants'),
  ('ELMENUS','restaurants'),
  ('UBEREATS','restaurants'),
  ('DELIVEROO','restaurants'),
  ('HUNGERSTATION','restaurants'),
  ('JAHEZ','restaurants'),
  ('NOONFOOD','restaurants'),
  ('CAREEMNOW','restaurants'),
  ('AMAZON','shopping'),
  ('AMZN','shopping'),
  ('NOON','shopping'),
  ('JUMIA','shopping'),
  ('SHEIN','shopping'),
  ('ALIEXPRESS','shopping'),
  ('TEMU','shopping'),
  ('CARREFOUR','shopping'),
  ('HYPERPANDA','shopping'),
  ('LULU','shopping'),
  ('NETFLIX','subscriptions'),
  ('SPOTIFY','subscriptions'),
  ('SHAHID','subscriptions'),
  ('OSN','subscriptions'),
  ('APPLE.COM/BILL','subscriptions'),
  ('GOOGLE','subscriptions'),
  ('YOUTUBE','subscriptions'),
  ('MICROSOFT','subscriptions'),
  ('ADOBE','subscriptions'),
  ('VODAFONE','bills'),
  ('ORANGE','bills'),
  ('ETISALAT','bills'),
  ('STC','bills'),
  ('MOBILY','bills'),
  ('ZAIN','bills'),
  ('OOREDOO','bills'),
  ('TOTAL','fuel'),
  ('SHELL','fuel'),
  ('MOBIL','fuel'),
  ('ENOC','fuel'),
  ('ADNOC','fuel'),
  ('WATANIA','fuel'),
  ('COOP','fuel'),
  ('BOOKING','travel'),
  ('AIRBNB','travel'),
  ('EXPEDIA','travel'),
  ('SKYSCANNER','travel'),
  ('EGYPTAIR','travel'),
  ('SAUDIA','travel'),
  ('EMIRATES','travel'),
  ('QATAR AIRWAYS','travel'),
  ('FLYDUBAI','travel'),
  ('FLYNAS','travel'),
  ('PHARMACY','health'),
  ('PHARMA','health'),
  ('SEIF','health'),
  ('ELEZABY','health'),
  ('NAHDI','health'),
  ('HOSPITAL','health'),
  ('CLINIC','health'),
  ('LAB','health'),
  ('COURSERA','education'),
  ('UDEMY','education'),
  ('EDX','education'),
  ('BRITISH COUNCIL','education'),
  ('DUOLINGO','education'),
  ('META ADS','subscriptions'),
  ('FACEBOOK ADS','subscriptions'),
  ('GOOGLE ADS','subscriptions'),
  ('TIKTOK ADS','subscriptions'),
  ('LINKEDIN ADS','subscriptions')
) AS v(keyword, category_key)
WHERE NOT EXISTS (SELECT 1 FROM merchant_keywords m WHERE m.keyword = v.keyword);
