-- Phase A: Supabase-primary ledger foundation.
--
-- DARK LAUNCH — these tables are NOT read or written by Flutter UI yet.
-- Drift remains the source of truth until Phase C of the gradual migration.
-- Phase 1/2 iOS capture relay (processed_captures) is unaffected.
--
-- Purpose: establish the schema and RLS policies now so that later phases
-- (dual-write in process-ios-sms, then full sync) can be enabled without
-- any schema changes on existing installs.

-- ── Shared updated_at trigger function ──────────────────────────────────────
-- Created once; reused by both tables below.
CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

-- ── user_transactions ────────────────────────────────────────────────────────
-- Mirrors the financial ledger that currently lives in Drift.
-- Eventually becomes the server source of truth (Phase C+).

CREATE TABLE IF NOT EXISTS public.user_transactions (
  id            UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id       UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,

  -- Idempotency key shared with processed_captures relay and iOS payloads.
  -- Scoped per user; the unique constraint is (user_id, payload_id).
  payload_id    TEXT        NULL,

  account_id    TEXT        NULL,     -- matches Drift account uuid (opaque ref for now)
  amount        NUMERIC     NOT NULL,
  currency      TEXT        NOT NULL, -- ISO 4217 e.g. SAR, AED, EGP
  type          TEXT        NOT NULL CHECK (type IN ('debit', 'credit', 'transfer', 'unknown')),
  merchant      TEXT        NULL,
  description   TEXT        NULL,
  category_id   TEXT        NULL,     -- stable category key e.g. 'restaurants'
  occurred_at   TIMESTAMPTZ NOT NULL,
  source        TEXT        NOT NULL CHECK (
    source IN ('ios_shortcut', 'android_sms', 'manual', 'import', 'share_extension')
  ),
  confidence    NUMERIC     NULL,     -- 0.0–1.0, NULL = not assessed
  raw_hash      TEXT        NULL,     -- fingerprint for dedup (same as capture_fingerprints)
  metadata      JSONB       NOT NULL DEFAULT '{}'::JSONB,

  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at    TIMESTAMPTZ NULL      -- soft-delete; NULL = live row
);

ALTER TABLE public.user_transactions ENABLE ROW LEVEL SECURITY;

-- Unique idempotency constraint scoped per user.
CREATE UNIQUE INDEX IF NOT EXISTS idx_user_transactions_user_payload
  ON public.user_transactions(user_id, payload_id)
  WHERE payload_id IS NOT NULL;

-- Primary query index: user's transaction history in reverse chronological order.
CREATE INDEX IF NOT EXISTS idx_user_transactions_user_occurred
  ON public.user_transactions(user_id, occurred_at DESC);

-- Soft-delete filter (WHERE deleted_at IS NULL is the common query path).
CREATE INDEX IF NOT EXISTS idx_user_transactions_user_deleted
  ON public.user_transactions(user_id, deleted_at);

-- RLS: users can only touch their own rows.
DROP POLICY IF EXISTS user_transactions_owner ON public.user_transactions;
CREATE POLICY user_transactions_owner
  ON public.user_transactions
  FOR ALL
  USING      (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

-- updated_at trigger.
DROP TRIGGER IF EXISTS trg_user_transactions_updated_at ON public.user_transactions;
CREATE TRIGGER trg_user_transactions_updated_at
  BEFORE UPDATE ON public.user_transactions
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ── user_smart_inbox ─────────────────────────────────────────────────────────
-- Inbox items generated by the backend (low-confidence captures, duplicates,
-- budget warnings, insights). Mirrors Drift's suspected_duplicates + future
-- Smart Inbox concept. Dark-launched in Phase A.

CREATE TABLE IF NOT EXISTS public.user_smart_inbox (
  id             UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id        UUID        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  transaction_id UUID        NULL REFERENCES public.user_transactions(id) ON DELETE SET NULL,

  -- payload_id allows correlating with a capture relay row before transaction_id is set.
  payload_id     TEXT        NULL,

  type           TEXT        NOT NULL CHECK (
    type IN ('needs_review', 'suspicious_duplicate', 'low_confidence', 'budget_warning', 'insight')
  ),
  title          TEXT        NOT NULL,
  body           TEXT        NULL,
  status         TEXT        NOT NULL DEFAULT 'open' CHECK (
    status IN ('open', 'resolved', 'dismissed')
  ),
  confidence     NUMERIC     NULL,
  metadata       JSONB       NOT NULL DEFAULT '{}'::JSONB,

  created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  deleted_at     TIMESTAMPTZ NULL
);

ALTER TABLE public.user_smart_inbox ENABLE ROW LEVEL SECURITY;

-- Primary query index: open inbox items newest-first.
CREATE INDEX IF NOT EXISTS idx_user_smart_inbox_user_status
  ON public.user_smart_inbox(user_id, status, created_at DESC);

-- payload_id lookup (correlate with relay before transaction is committed).
CREATE INDEX IF NOT EXISTS idx_user_smart_inbox_user_payload
  ON public.user_smart_inbox(user_id, payload_id)
  WHERE payload_id IS NOT NULL;

-- RLS: users can only touch their own rows.
DROP POLICY IF EXISTS user_smart_inbox_owner ON public.user_smart_inbox;
CREATE POLICY user_smart_inbox_owner
  ON public.user_smart_inbox
  FOR ALL
  USING      (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

-- updated_at trigger.
DROP TRIGGER IF EXISTS trg_user_smart_inbox_updated_at ON public.user_smart_inbox;
CREATE TRIGGER trg_user_smart_inbox_updated_at
  BEFORE UPDATE ON public.user_smart_inbox
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
