-- 0094 — canonical merchant catalog (COUPONS Phase 1).
--
-- Coupons today carry a free-text `partner_name`. That is enough to display an
-- offer and useless for deciding whether an offer is relevant to a user, because
-- "NOON", "noon.com" and "نون" are three strings and one company. This migration
-- adds the server-authored canonical merchant identity plus the reviewed aliases
-- that map real bank-message merchant strings onto it.
--
-- WHAT THIS DELIBERATELY IS NOT
--
-- It is not a personalization service. Merchant resolution and interest scoring
-- happen ENTIRELY ON DEVICE, from the local transaction ledger, and nothing
-- derived from a user's spending is ever sent here. The server publishes a
-- catalog; the device decides what it means. That is why there is no user column
-- anywhere in this file.
--
-- It is not fuzzy matching. An alias resolves exactly or the device abstains.
-- For categorization a false match costs a wrong chip; for "you shop here a lot"
-- derived from someone's bank messages, a false match is a trust breach in a
-- finance app. Recall is an alias-coverage problem solved by data — NOON,
-- NOONCOM, NOON KSA, noon.com as four reviewed aliases — not by an algorithm
-- that guesses.

-- ---------------------------------------------------------------------------
-- 1. The frozen key functions
--
-- GENERATED from docs/coupons/merchant_alias_key_v1.tables.json by
-- tools/coupons/gen_merchant_alias_key.py. The same source generates the Dart
-- implementation, because the device must resolve offline (so it cannot ask the
-- server for a key) while the uniqueness index needs the key in an index
-- expression (so it cannot call Dart). Duplication is forced; drift is the risk;
-- one source plus `--check` in CI is the control.
--
-- Do not edit between the markers. Run the generator.
-- ---------------------------------------------------------------------------

-- >>> BEGIN GENERATED merchant_alias_key_v1 >>>
-- GENERATED by tools/coupons/gen_merchant_alias_key.py — DO NOT EDIT BY HAND.
-- Source of truth: docs/coupons/merchant_alias_key_v1.tables.json
-- Specification:   docs/coupons/MERCHANT_ALIAS_KEY_V1.md
--
-- INJECTED into 0094_catalog_merchants.sql between markers. It is not a
-- standalone migration: a .sql file in a subdirectory is not applied by
-- `supabase db push`, and a second copy would be the drift this design prevents.
--
-- IMMUTABLE is required: the function backs a STORED generated column and a
-- partial unique index. Every operation used here (translate, regexp_replace
-- with an enumerated class, btrim on ASCII space) is collation-independent.
--
-- NEVER `CREATE OR REPLACE` this function. PostgreSQL permits it, does not
-- recompute stored generated columns, and does not rebuild dependent indexes —
-- the result is silently stale keys with no error anywhere.

CREATE OR REPLACE FUNCTION merchant_alias_key_v1(input TEXT)
RETURNS TEXT
LANGUAGE sql
IMMUTABLE
PARALLEL SAFE
RETURNS NULL ON NULL INPUT
AS $$
  SELECT btrim(
    regexp_replace(
      regexp_replace(
        -- step 5: fold Arabic-Indic + Eastern Arabic-Indic digits, KEEP them
        translate(
          -- step 4: letter folds
          translate(
            -- step 3: delete diacritics and tatweel
            translate(
              -- step 2: ASCII case fold only
              translate(input, U&'\0041\0042\0043\0044\0045\0046\0047\0048\0049\004A\004B\004C\004D\004E\004F\0050\0051\0052\0053\0054\0055\0056\0057\0058\0059\005A', U&'\0061\0062\0063\0064\0065\0066\0067\0068\0069\006A\006B\006C\006D\006E\006F\0070\0071\0072\0073\0074\0075\0076\0077\0078\0079\007A'),
              U&'\0610\0611\0612\0613\0614\0615\0616\0617\0618\0619\061A\0640\064B\064C\064D\064E\064F\0650\0651\0652\0653\0654\0655\0656\0657\0658\0659\065A\065B\065C\065D\065E\065F\0670', ''
            ),
            U&'\0622\0623\0624\0625\0626\0629\0649\0671\06A9\06CC', U&'\0627\0627\0648\0627\064A\0647\064A\0627\0643\064A'
          ),
          U&'\0660\0661\0662\0663\0664\0665\0666\0667\0668\0669\06F0\06F1\06F2\06F3\06F4\06F5\06F6\06F7\06F8\06F9', U&'\0030\0031\0032\0033\0034\0035\0036\0037\0038\0039\0030\0031\0032\0033\0034\0035\0036\0037\0038\0039'
        ),
        -- step 6: everything outside the KEEP set becomes one space.
        -- Enumerated, never a range: PostgreSQL bracket ranges are
        -- collating-sequence dependent.
        '[^' || U&'\0030\0031\0032\0033\0034\0035\0036\0037\0038\0039\0061\0062\0063\0064\0065\0066\0067\0068\0069\006A\006B\006C\006D\006E\006F\0070\0071\0072\0073\0074\0075\0076\0077\0078\0079\007A\0620\0621\0622\0623\0624\0625\0626\0627\0628\0629\062A\062B\062C\062D\062E\062F\0630\0631\0632\0633\0634\0635\0636\0637\0638\0639\063A\063B\063C\063D\063E\063F\0641\0642\0643\0644\0645\0646\0647\0648\0649\064A\066E\066F\0671\0672\0673\0674\0675\0676\0677\0678\0679\067A\067B\067C\067D\067E\067F\0680\0681\0682\0683\0684\0685\0686\0687\0688\0689\068A\068B\068C\068D\068E\068F\0690\0691\0692\0693\0694\0695\0696\0697\0698\0699\069A\069B\069C\069D\069E\069F\06A0\06A1\06A2\06A3\06A4\06A5\06A6\06A7\06A8\06A9\06AA\06AB\06AC\06AD\06AE\06AF\06B0\06B1\06B2\06B3\06B4\06B5\06B6\06B7\06B8\06B9\06BA\06BB\06BC\06BD\06BE\06BF\06C0\06C1\06C2\06C3\06C4\06C5\06C6\06C7\06C8\06C9\06CA\06CB\06CC\06CD\06CE\06CF\06D0\06D1\06D2\06D3\06D5\06E5\06E6\06EE\06EF\06FA\06FB\06FC\06FF' || ']', ' ', 'g'
      ),
      -- step 7: collapse runs of ASCII space
      ' +', ' ', 'g'
    ),
    ' '  -- step 8: trim ASCII space ONLY (btrim's default set is ASCII space)
  );
$$;

COMMENT ON FUNCTION merchant_alias_key_v1(TEXT) IS
  'FROZEN v1 merchant-name lookup key. See docs/coupons/MERCHANT_ALIAS_KEY_V1.md. Never edit in place.';

-- Domain keys are a SEPARATE contract: digits, dots and hyphens are
-- semantically load-bearing in a hostname, so `7eleven.com` must never fold the
-- way a name does. Takes an ALREADY-EXTRACTED host — URL parsing and IDNA
-- happen upstream on the client, because PostgreSQL ships neither and a
-- mismatched IDNA implementation is exactly the drift this design prevents.
CREATE OR REPLACE FUNCTION merchant_domain_key_v1(input TEXT)
RETURNS TEXT
LANGUAGE sql
IMMUTABLE
PARALLEL SAFE
RETURNS NULL ON NULL INPUT
AS $$
  SELECT CASE
    WHEN host ~ '^[a-z0-9]([a-z0-9-]*[a-z0-9])?(\.[a-z0-9]([a-z0-9-]*[a-z0-9])?)+$'
      THEN host
    ELSE ''
  END
  FROM (
    SELECT regexp_replace(
             regexp_replace(
               translate(btrim(input, ' '), U&'\0041\0042\0043\0044\0045\0046\0047\0048\0049\004A\004B\004C\004D\004E\004F\0050\0051\0052\0053\0054\0055\0056\0057\0058\0059\005A', U&'\0061\0062\0063\0064\0065\0066\0067\0068\0069\006A\006B\006C\006D\006E\006F\0070\0071\0072\0073\0074\0075\0076\0077\0078\0079\007A'),
               '^www\.', ''
             ),
             '\.$', ''
           ) AS host
  ) s;
$$;

COMMENT ON FUNCTION merchant_domain_key_v1(TEXT) IS
  'FROZEN v1 merchant-domain lookup key. Host only, never a URL. Never edit in place.';
-- <<< END GENERATED merchant_alias_key_v1 <<<

-- ---------------------------------------------------------------------------
-- 2. merchant_lookup_noise_v1 — the write guard's predicate
--
-- The device's lookup pipeline removes acquirer boilerplate and
-- marker-introduced identifiers BEFORE looking a merchant up. That stripping is
-- deliberately outside the frozen key (a lexicon inside the key would make every
-- new bank prefix a full key-version migration). The cost of that choice is that
-- the catalog must never contain an alias the pipeline would strip — otherwise
-- the same string resolves differently depending on which stage matched it:
--
--   alias `cafe term 4471` -> merchant A,  alias `cafe` -> merchant B
--   query "CAFE TERM 4471" hits A unstripped, and B if stripped first.
--
-- The system cannot call a suffix noise and simultaneously allow it inside a
-- reviewed identity. So this predicate recognises EVERY construct the pipeline
-- can remove, and the trigger below rejects any alias containing one.
--
-- It runs on the CANONICALISED form, never on raw text: a whitespace-only regex
-- is evadable, because `POS-PURCHASE CARREFOUR` becomes `pos purchase carrefour`
-- on the device but never matches `\s`-based matching on the raw string.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION merchant_lookup_noise_v1(input TEXT)
RETURNS BOOLEAN
LANGUAGE sql
IMMUTABLE
PARALLEL SAFE
AS $$
  SELECT k ~ (
      -- anchored multi-word acquirer wrappers. Bare `pos`, `purchase`,
      -- `payment`, `شراء`, `دفع` are deliberately ABSENT: they are plausible
      -- beginnings of real business names, and stripping them turns
      -- "PAYMENT SOLUTIONS" into a different merchant called "Solutions".
      '^(pos purchase|card purchase|purchase at|payment to|point of sale'
      || '|شراء من|مشتريات من|عمليه شراء|دفع الى) '
    )
    OR k ~ (
      -- marker-introduced identifiers. The digits are REQUIRED (`+`, not `*`):
      -- text_normalizer.dart:36 uses `*`, which strips a bare trailing token and
      -- turns "CAFE TRACE" into "CAFE".
      '(^| )(branch|term|terminal|ref|txn|trace|auth|فرع|ترمينال|مرجع) [0-9]+( |$)'
    )
  FROM (SELECT merchant_alias_key_v1(input) AS k) s;
$$;

COMMENT ON FUNCTION merchant_lookup_noise_v1(TEXT) IS
  'True when a string contains something MerchantLookupPipeline.v1 would strip. Mirrors the client lexicon; see docs/coupons/MERCHANT_ALIAS_KEY_V1.md.';

-- ---------------------------------------------------------------------------
-- 3. catalog_merchants
-- ---------------------------------------------------------------------------
CREATE SEQUENCE IF NOT EXISTS catalog_seq_catalog_merchants;
CREATE SEQUENCE IF NOT EXISTS catalog_seq_merchant_aliases;

CREATE TABLE IF NOT EXISTS catalog_merchants (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  slug          TEXT NOT NULL UNIQUE,
  name_ar       TEXT NOT NULL,
  name_en       TEXT,
  primary_domain TEXT,
  logo_path     TEXT,
  default_display_category_key TEXT REFERENCES coupon_categories(key),
  -- {} means global. Same convention as coupons.country_codes.
  country_codes TEXT[] NOT NULL DEFAULT '{}',
  is_active     BOOLEAN NOT NULL DEFAULT TRUE,
  -- Tombstone, never hard-deleted: a delta client that never sees the row
  -- disappear would keep a merchant forever.
  is_deleted    BOOLEAN NOT NULL DEFAULT FALSE,
  created_version BIGINT NOT NULL DEFAULT 0,
  updated_version BIGINT NOT NULL DEFAULT 0,
  deleted_version BIGINT,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT now(),

  CONSTRAINT catalog_merchants_slug_shape CHECK (slug ~ '^[a-z0-9][a-z0-9-]{1,62}$'),
  CONSTRAINT catalog_merchants_name_ar_present CHECK (btrim(name_ar) <> ''),
  -- Mirrors coupons_country_codes_shape (0081): array_to_string keeps it a
  -- simple immutable expression, since CHECK cannot contain a subquery.
  CONSTRAINT catalog_merchants_country_codes_shape CHECK (
    country_codes = '{}'::text[]
    OR array_to_string(country_codes, ',') ~ '^[A-Z]{2}(,[A-Z]{2})*$'
  ),
  -- Server-derived storage path only; never a client-shaped or traversing one.
  CONSTRAINT catalog_merchants_logo_path_shape CHECK (
    logo_path IS NULL OR logo_path ~ '^merchants/[0-9a-f-]{36}/[A-Za-z0-9_.-]+$'
  ),
  -- A domain here is a HOST, matching merchant_domain_key_v1's contract.
  CONSTRAINT catalog_merchants_primary_domain_shape CHECK (
    primary_domain IS NULL
    OR primary_domain = merchant_domain_key_v1(primary_domain)
  )
);

CREATE INDEX IF NOT EXISTS idx_catalog_merchants_live
  ON catalog_merchants (is_active) WHERE NOT is_deleted;

-- ---------------------------------------------------------------------------
-- 4. catalog_merchant_aliases
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS catalog_merchant_aliases (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  merchant_id UUID NOT NULL REFERENCES catalog_merchants(id) ON DELETE CASCADE,

  -- The value a human entered. Kept because merchant_id is the identity and
  -- alias_normalized is only a lookup key: without the original there is nothing
  -- to review, debug, or re-key against when a v2 key function arrives.
  alias_raw   TEXT NOT NULL,

  alias_kind  TEXT NOT NULL,

  -- DERIVED, never supplied. PostgreSQL rejects an explicit value for a
  -- GENERATED ALWAYS column outright — there is no OVERRIDING escape hatch as
  -- there is for identity columns — so an admin request cannot smuggle a key
  -- that does not match its own raw value.
  alias_normalized TEXT GENERATED ALWAYS AS (
    CASE alias_kind
      WHEN 'name'   THEN merchant_alias_key_v1(alias_raw)
      WHEN 'domain' THEN merchant_domain_key_v1(alias_raw)
    END
  ) STORED,

  key_version INT NOT NULL DEFAULT 1,

  -- NULL means global.
  country_code TEXT,
  priority     INT NOT NULL DEFAULT 0,
  provenance   TEXT NOT NULL DEFAULT 'admin',
  -- Provider-suggested aliases arrive unreviewed and are NOT served to devices.
  is_reviewed  BOOLEAN NOT NULL DEFAULT FALSE,
  is_active    BOOLEAN NOT NULL DEFAULT TRUE,
  is_deleted   BOOLEAN NOT NULL DEFAULT FALSE,
  created_version BIGINT NOT NULL DEFAULT 0,
  updated_version BIGINT NOT NULL DEFAULT 0,
  deleted_version BIGINT,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- NOT NULL + CHECK together: without both, the CASE above falls through to
  -- NULL and the alias silently has no key.
  CONSTRAINT catalog_merchant_aliases_kind CHECK (alias_kind IN ('name','domain')),
  CONSTRAINT catalog_merchant_aliases_provenance
    CHECK (provenance IN ('admin','provider','observed_candidate')),
  CONSTRAINT catalog_merchant_aliases_country_shape
    CHECK (country_code IS NULL OR country_code ~ '^[A-Z]{2}$'),
  -- Only v1 exists. An unconstrained, admin-writable version label would be a
  -- lie waiting to happen.
  CONSTRAINT catalog_merchant_aliases_key_version CHECK (key_version = 1),
  -- THE empty-key guard. Every input that folds away — all punctuation, all
  -- diacritics, a rejected Unicode host — produces ''. Without this they would
  -- all share one key and match each other.
  CONSTRAINT catalog_merchant_aliases_key_nonempty CHECK (alias_normalized <> ''),
  CONSTRAINT catalog_merchant_aliases_raw_present CHECK (btrim(alias_raw) <> '')
);

-- An active REVIEWED alias resolves to exactly one merchant. Scoped on
-- COALESCE(country_code,'') so a global row and a country row may legitimately
-- coexist — the device abstains between them unless it has merchant-location
-- evidence.
--
-- A partial unique INDEX, not a table constraint: PostgreSQL has no
-- `UNIQUE (...) WHERE ...` constraint syntax, and the expression rules it out
-- besides.
CREATE UNIQUE INDEX IF NOT EXISTS idx_merchant_aliases_unique_live
  ON catalog_merchant_aliases (alias_normalized, alias_kind, COALESCE(country_code, ''))
  WHERE is_active AND NOT is_deleted AND is_reviewed;

CREATE INDEX IF NOT EXISTS idx_merchant_aliases_merchant
  ON catalog_merchant_aliases (merchant_id) WHERE NOT is_deleted;
CREATE INDEX IF NOT EXISTS idx_merchant_aliases_review_queue
  ON catalog_merchant_aliases (is_reviewed, created_at) WHERE NOT is_deleted;

-- ---------------------------------------------------------------------------
-- 5. The write guard
--
-- Runs BEFORE, on NEW.alias_raw. It cannot read NEW.alias_normalized: generated
-- columns are computed AFTER before-triggers.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION trg_guard_merchant_alias() RETURNS TRIGGER AS $$
BEGIN
  IF NEW.alias_kind = 'name' AND merchant_lookup_noise_v1(NEW.alias_raw) THEN
    RAISE EXCEPTION
      'alias % contains acquirer boilerplate or a marker identifier that the device would strip before lookup; store the merchant name alone',
      NEW.alias_raw
      USING ERRCODE = 'check_violation';
  END IF;
  NEW.updated_at := now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_merchant_aliases_guard ON catalog_merchant_aliases;
CREATE TRIGGER trg_merchant_aliases_guard
  BEFORE INSERT OR UPDATE ON catalog_merchant_aliases
  FOR EACH ROW EXECUTE FUNCTION trg_guard_merchant_alias();

DROP TRIGGER IF EXISTS trg_catalog_merchants_updated_at ON catalog_merchants;
CREATE TRIGGER trg_catalog_merchants_updated_at
  BEFORE UPDATE ON catalog_merchants
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ---------------------------------------------------------------------------
-- 6. Delta versioning — the 0002 idiom, with 0093's lesson applied
--
-- 0006 shipped merchant_keywords with a catalog_versions row and no trigger to
-- bump it, so every device that synced once was pinned forever. These tables
-- get their bump at creation time, not later.
-- ---------------------------------------------------------------------------
INSERT INTO catalog_versions (category, version, updated_at) VALUES
  ('catalog_merchants', 1, now()),
  ('merchant_aliases',  1, now())
ON CONFLICT (category) DO NOTHING;

CREATE OR REPLACE FUNCTION trg_version_catalog_merchants() RETURNS TRIGGER AS $$
DECLARE v BIGINT;
BEGIN
  v := nextval('catalog_seq_catalog_merchants');
  IF TG_OP = 'INSERT' THEN
    NEW.created_version := v; NEW.updated_version := v;
  ELSIF TG_OP = 'UPDATE' THEN
    NEW.updated_version := v;
    IF NEW.is_deleted AND NOT OLD.is_deleted THEN NEW.deleted_version := v; END IF;
  END IF;
  UPDATE catalog_versions SET version = v, updated_at = now()
   WHERE category = 'catalog_merchants';
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_catalog_merchants_version ON catalog_merchants;
CREATE TRIGGER trg_catalog_merchants_version
  BEFORE INSERT OR UPDATE ON catalog_merchants
  FOR EACH ROW EXECUTE FUNCTION trg_version_catalog_merchants();

CREATE OR REPLACE FUNCTION trg_version_merchant_aliases() RETURNS TRIGGER AS $$
DECLARE v BIGINT;
BEGIN
  v := nextval('catalog_seq_merchant_aliases');
  IF TG_OP = 'INSERT' THEN
    NEW.created_version := v; NEW.updated_version := v;
  ELSIF TG_OP = 'UPDATE' THEN
    NEW.updated_version := v;
    IF NEW.is_deleted AND NOT OLD.is_deleted THEN NEW.deleted_version := v; END IF;
  END IF;
  UPDATE catalog_versions SET version = v, updated_at = now()
   WHERE category = 'merchant_aliases';
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_merchant_aliases_version ON catalog_merchant_aliases;
CREATE TRIGGER trg_merchant_aliases_version
  BEFORE INSERT OR UPDATE ON catalog_merchant_aliases
  FOR EACH ROW EXECUTE FUNCTION trg_version_merchant_aliases();

-- A hard DELETE also changes what a device should see. Statement-level, because
-- the row is gone and only the counter matters.
CREATE OR REPLACE FUNCTION trg_version_bump_on_delete() RETURNS TRIGGER AS $$
BEGIN
  IF TG_TABLE_NAME = 'catalog_merchants' THEN
    UPDATE catalog_versions
       SET version = nextval('catalog_seq_catalog_merchants'), updated_at = now()
     WHERE category = 'catalog_merchants';
  ELSE
    UPDATE catalog_versions
       SET version = nextval('catalog_seq_merchant_aliases'), updated_at = now()
     WHERE category = 'merchant_aliases';
  END IF;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_catalog_merchants_version_del ON catalog_merchants;
CREATE TRIGGER trg_catalog_merchants_version_del
  AFTER DELETE ON catalog_merchants
  FOR EACH STATEMENT EXECUTE FUNCTION trg_version_bump_on_delete();

DROP TRIGGER IF EXISTS trg_merchant_aliases_version_del ON catalog_merchant_aliases;
CREATE TRIGGER trg_merchant_aliases_version_del
  AFTER DELETE ON catalog_merchant_aliases
  FOR EACH STATEMENT EXECUTE FUNCTION trg_version_bump_on_delete();

-- ---------------------------------------------------------------------------
-- 7. RLS — read-only catalog, per-role, 0081 idiom
--
-- Aliases additionally require is_reviewed: an unreviewed provider suggestion
-- must never reach a device, or the review step would be decorative.
-- ---------------------------------------------------------------------------
ALTER TABLE catalog_merchants         ENABLE ROW LEVEL SECURITY;
ALTER TABLE catalog_merchant_aliases  ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS catalog_merchants_select_anon ON catalog_merchants;
CREATE POLICY catalog_merchants_select_anon ON catalog_merchants
  FOR SELECT TO anon USING (is_active AND NOT is_deleted);
DROP POLICY IF EXISTS catalog_merchants_select_authenticated ON catalog_merchants;
CREATE POLICY catalog_merchants_select_authenticated ON catalog_merchants
  FOR SELECT TO authenticated USING (is_active AND NOT is_deleted);

DROP POLICY IF EXISTS merchant_aliases_select_anon ON catalog_merchant_aliases;
CREATE POLICY merchant_aliases_select_anon ON catalog_merchant_aliases
  FOR SELECT TO anon USING (is_active AND NOT is_deleted AND is_reviewed);
DROP POLICY IF EXISTS merchant_aliases_select_authenticated ON catalog_merchant_aliases;
CREATE POLICY merchant_aliases_select_authenticated ON catalog_merchant_aliases
  FOR SELECT TO authenticated USING (is_active AND NOT is_deleted AND is_reviewed);

-- Supabase grants anon/authenticated a broad default DML set on every new public
-- table. Revoke first, then grant only SELECT — the 0079/0088 idiom.
REVOKE ALL ON TABLE catalog_merchants, catalog_merchant_aliases
  FROM anon, authenticated;
GRANT SELECT ON TABLE catalog_merchants, catalog_merchant_aliases
  TO anon, authenticated;

-- ---------------------------------------------------------------------------
-- 8. Verification — fail the migration rather than report a half-applied one
-- ---------------------------------------------------------------------------
DO $$
DECLARE n INT; k TEXT;
BEGIN
  -- the generated column must actually be generated
  SELECT is_generated INTO k FROM information_schema.columns
   WHERE table_name = 'catalog_merchant_aliases' AND column_name = 'alias_normalized';
  IF k IS DISTINCT FROM 'ALWAYS' THEN
    RAISE EXCEPTION '0094: alias_normalized is not a generated column (%)', k;
  END IF;

  SELECT count(*) INTO n FROM pg_indexes
   WHERE tablename = 'catalog_merchant_aliases'
     AND indexname = 'idx_merchant_aliases_unique_live';
  IF n <> 1 THEN RAISE EXCEPTION '0094: the alias uniqueness index is missing'; END IF;

  SELECT count(*) INTO n FROM catalog_versions
   WHERE category IN ('catalog_merchants','merchant_aliases');
  IF n <> 2 THEN RAISE EXCEPTION '0094: catalog_versions rows missing (%)', n; END IF;

  -- the frozen keys must behave; a silent regeneration error would otherwise
  -- only surface as merchants that never resolve on device
  IF merchant_alias_key_v1('  CARREFOUR 24  ') <> 'carrefour 24' THEN
    RAISE EXCEPTION '0094: merchant_alias_key_v1 is not the frozen v1 contract';
  END IF;
  IF merchant_domain_key_v1('WWW.7Eleven.com.') <> '7eleven.com' THEN
    RAISE EXCEPTION '0094: merchant_domain_key_v1 is not the frozen v1 contract';
  END IF;
  IF NOT merchant_lookup_noise_v1('POS PURCHASE CARREFOUR')
     OR NOT merchant_lookup_noise_v1('CAFE TERM 4471')
     OR merchant_lookup_noise_v1('PAYMENT SOLUTIONS')
     OR merchant_lookup_noise_v1('CAFE TRACE') THEN
    RAISE EXCEPTION '0094: merchant_lookup_noise_v1 does not match the client lexicon';
  END IF;
END $$;
