#!/usr/bin/env bash
# PRE-ARCHIVE PREFLIGHT — run this immediately before `flutter build ipa`.
#
# Exists because `ios/Flutter/Generated.xcconfig` is REGENERATED by every build
# and by every `flutter test -d <device>` run, and the integration suite passes
# QA_EMAIL / QA_PASSWORD / QA_USER_ID as dart-defines. Run the QA suite, then
# archive without an intervening clean release build, and those credentials
# compile into the shipped binary.
#
# That is not hypothetical: it was the live state of this working copy on
# 2026-09-16 after a day of integration runs.
#
# Checks the SHIPPED ARTIFACT, not the source, because the source was never the
# risk.
set -uo pipefail
cd "$(dirname "$0")/.."

fail=0
say() { printf '%-52s %s\n' "$1" "$2"; }
check() { if [ "$2" = "0" ]; then say "$1" "OK"; else say "$1" "*** FAIL ***"; fail=1; fi }

echo "── build configuration ─────────────────────────────────────"

if [ -f ios/Flutter/Generated.xcconfig ]; then
  defines=$(python3 - <<'PY'
import base64
try:
    line = [l for l in open('ios/Flutter/Generated.xcconfig') if l.startswith('DART_DEFINES=')][0]
except IndexError:
    print(''); raise SystemExit
out = []
for v in line.split('=', 1)[1].strip().split(','):
    try:
        out.append(base64.b64decode(v).decode('utf-8', 'replace').split('=')[0])
    except Exception:
        pass
print('\n'.join(out))
PY
)
  qa=$(printf '%s\n' "$defines" | grep -cE '^(QA_|SWEEP_)' || true)
  check "no QA/SWEEP dart-defines in Generated.xcconfig" "$qa"
  sup=$(printf '%s\n' "$defines" | grep -c '^SUPABASE_' || true)
  if [ "$sup" -ge 2 ]; then say "SUPABASE_URL + ANON_KEY present" "OK"
  else say "SUPABASE_URL + ANON_KEY present" "*** FAIL (release fails closed without them) ***"; fail=1; fi
else
  say "Generated.xcconfig exists" "*** FAIL ***"; fail=1
fi

ver=$(grep '^version:' pubspec.yaml | awk '{print $2}')
say "pubspec version" "$ver"
pub=$(grep -o "kPubspecVersion = '[^']*'" lib/core/backend/app_version.dart | cut -d"'" -f2)
check "kPubspecVersion matches pubspec" "$([ "${ver%%+*}" = "$pub" ] && echo 0 || echo 1)"

echo
echo "── the built artifact ──────────────────────────────────────"
APP=build/ios/iphoneos/Runner.app
# BOTH binaries. dart-defines are compiled into the Dart snapshot inside
# App.framework, NOT into the Runner Mach-O — checking only `Runner` finds
# nothing and reports a clean bill of health for a binary full of secrets.
BINARIES="$APP/Runner $APP/Frameworks/App.framework/App"
if [ -d "$APP" ]; then
  scan() { for b in $BINARIES; do [ -f "$b" ] && strings "$b" 2>/dev/null; done | grep -c "$1" || true; }
  for needle in QA_EMAIL QA_PASSWORD QA_USER_ID service_role youssefsafwat1223; do
    check "no '$needle' in the app binaries" "$(scan "$needle")"
  done
  prod=$(scan 'rjwphwsefnuotpbtuycf')
  if [ "$prod" -gt 0 ]; then say "production project ref present ($prod)" "OK"
  else say "production project ref present" "*** FAIL — wrong or missing config ***"; fail=1; fi
  for ref in vrombzdgwqjjiijbidqb dpdukyozedajelflkeix bdhqjijscwdzqwqanygv; do
    check "no ZERO-CONTACT ref '$ref'" "$(scan "$ref")"
  done
  v=$(plutil -extract CFBundleShortVersionString raw "$APP/Info.plist" 2>/dev/null)
  b=$(plutil -extract CFBundleVersion raw "$APP/Info.plist" 2>/dev/null)
  id=$(plutil -extract CFBundleIdentifier raw "$APP/Info.plist" 2>/dev/null)
  say "artifact version" "$v ($b)"
  check "artifact bundle id is com.youssefsafwat.mali" \
    "$([ "$id" = "com.youssefsafwat.mali" ] && echo 0 || echo 1)"
  check "artifact version matches pubspec" \
    "$([ "$v" = "${ver%%+*}" ] && echo 0 || echo 1)"
else
  say "built Runner.app present" "SKIPPED (build first)"
fi

echo
echo "── privacy posture ─────────────────────────────────────────"
ats=$(plutil -p ios/Runner/Info.plist 2>/dev/null | grep -c NSAppTransportSecurity || true)
check "ATS enforced (no exception dictionary)" "$ats"
att=$(grep -c NSUserTrackingUsageDescription ios/Runner/Info.plist || true)
check "no ATT string while ads are non-personalized" "$att"

echo
if [ "$fail" = "0" ]; then
  echo "PREFLIGHT PASS — safe to archive."
else
  echo "PREFLIGHT FAILED — do NOT archive until the starred lines are fixed."
fi
exit "$fail"
